theme: jekyll-theme-cayman
github:
  is_project_page: false
title: "Attention PGH Crafters, Markets, Designs"
description: "Growing your business: A workshop on how to get the feedback you need from your social media"
