theme: jekyll-theme-cayman
github:
  is_project_page: false
title: "Calling all PGH Crafters, Makers, Designers"
description: "A workshop on how to get the feedback you need from your social media, and ultimately grow your small business. Hosted by Carnegie-Mellon University, Prototype PGH and MAC Makerspace"
