theme: jekyll-theme-cayman
github:
  is_project_page: false
title: "Calling all PGH Crafters, Markets, Designs"
description: "Growing your small business: A workshop on how to get the feedback you need from your social media"
